### ISSUE TITLE
Extract workflows from histories

### ISSUE THREAD

**Issue by jibe-b** [galaxyproject/bioblend#204]
Is there a method that either:
- create a workflow in the db from an history
- enable to download a workflow corresponding to an history?

**Comment by nsoranzo** [comment]
>- create a workflow in the db from an history

There is presently no BioBlend method to do that, but it shouldn't be too difficult to create one since this is supported by the Galaxy API, see https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/workflows.py#L129

>- enable to download a workflow corresponding to an history?

There is no BioBlend or Galaxy API to do that, but once the above is implemented, you can extract the workflow from the history and then download it using https://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#bioblend.galaxy.workflows.WorkflowClient.export_workflow_to_local_path

**Comment by jibe-b** [comment]
Thanks, I now see how to do it.

But when I try to POST 

> ./create.py  $key http://localhost:8080/api/workflows?from_history_id=5969b1f7201f12ae&workflow_name=w0

there is the error 400:

> {"err_msg": "One parameter among - from_history_id, workflow_id, workflow, shared_workflow_id, installed_repository_file - must be specified", "err_code": 400007}

**Comment by jibe-b** [comment]
when passing
> /api/workflows?from_history_id=5969b1f7201f12ae&workflow_id=123

the error does not appear but I know it should be wrong (the workflow with this workflow_id does not exist) and it does not create a workflow in the database.

**Comment by nsoranzo** [comment]
You're passing `from_history_id` in the query string, while it should be in the request body (also known as payload).
See https://docs.google.com/presentation/d/12wts6oaUH4TLKYMYBzCZPYI3Jf1wzl1ecK0IeCVkJ4s/edit#slide=id.gb334432d9_0_31 , and https://github.com/nsoranzo/bioblend-tutorial for some examples.

**Comment by jibe-b** [comment]
Ok, so I stopped using the intermediary scripts provided with galaxy to work directly with curl

>curl -H "Content-Type: application/json" http://localhost:8080/api/workflows?key=$KEY --data @payload.json

with payload.json containing: 

>{"from_history_id": "f597429621d6eb2b", "workflow_name": "w0"}
