### ISSUE TITLE
download dataset using local copy

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/bioblend#28]
Curious to see if anyone would be interesting for the ability to copy a dataset using shutil.copyfile if the dataset file path is accessible. It would be useful in cases when you want to avoid sending a huge file(s) through a http get request and where both your galaxy instance and local machine share a common storage backend. 

Anyone be interested? Got some code that does it....

**Comment by nsoranzo** [comment]
The path of the file is already available for admin users using `gi.datasets.show_dataset(dataset_id)['file_name']`. Is that enough?

**Comment by erasche** [comment]
There's a flag you can pass in Galaxy's config that exposes the real dataset path. It's used in (I think) CSIRO's Galaxy VMs in order to allow other services to connect to galaxy and pull data as they're running under the same user. Perhaps this is a similar scenario to what @Takadonet is referring to?

**Comment by nsoranzo** [comment]
`expose_dataset_path` directive in `config/galaxy.ini` would indeed expose the dataset path also to non-admin users, which can again be retrieved with `gi.datasets.show_dataset(dataset_id)['file_name']`.
